export enum HomeSectionType {
  HERO_SLIDER = "HERO_SLIDER",
  TILE_ROW = "TILE_ROW",
  BANNER = "BANNER",
  BRAND_CAROUSEL = "BRAND_CAROUSEL",
  SPOTLIGHT = "SPOTLIGHT",
  PRODUCT_RAIL = "PRODUCT_RAIL",
  TRUST_STRIP = "TRUST_STRIP",
  SOCIAL_LINKS = "SOCIAL_LINKS",
  FAQ = "FAQ",
  TESTIMONIALS = "TESTIMONIALS",
  BRANCH_MAP = "BRANCH_MAP",
}

export enum ProductRailSource {
  CATEGORY = "CATEGORY",
  PRODUCTS = "PRODUCTS",
}
