/** Model names. Also the `entityName` repositories report in NotFound errors. */
export enum EntityName {
  BRAND = "Brand",
  CART = "Cart",
  CATEGORY = "Category",
  COUPON = "Coupon",
  CUSTOMER = "Customer",
  FAQ = "Faq",
  HOME_SECTION = "HomeSection",
  IDEMPOTENCY_RECORD = "IdempotencyRecord",
  NEWSLETTER_SUBSCRIBER = "NewsletterSubscriber",
  ORDER = "Order",
  ORDER_SEQUENCE = "OrderSequence",
  PAGE = "Page",
  POST = "Post",
  PRODUCT = "Product",
  ADMIN_REFRESH_TOKEN = "AdminRefreshToken",
  REVIEW = "Review",
  STORE_SETTINGS = "StoreSettings",
  TESTIMONIAL = "Testimonial",
}
